global using api.Models;
global using api.Settings;
global using api.interfaces;
global using api.DTOs;
global using MongoDB.Driver;
global using MongoDB.Bson;
global using MongoDB.Bson.Serialization.Attributes;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Mvc;